### ISSUE TITLE
Record then render?

### ISSUE THREAD

**Issue by pawamoy** [laffra/pynsights#3]
So, as I understand, pynsights currently only works "live": it traces calls in realtime and serves them via an HTTP server, that the web page calls to get the data and render it (correct me if I'm wrong, and technical details are welcome!).

What would be awesome is the ability to *record* the data, so as to replay it again and again, with different rendering options! This way it could be integrated into documentation pages (a bit of HTML and JS?), where readers could then "play" the execution of code and see what happens, zooming in the parts they're interested in.

Then other features could be added like the speed of the dots, whether to show only one dot at a time (to very precisely see the whole chain of calls, one at a time), finer-grain nodes (functions/callables themselves) etc.

But I should probably ask first: do you have a todo list of some kind :smile:? Really curious to know what you're planning for this great tool :slightly_smiling_face:

**Comment by laffra** [comment]
I had similar thoughts... Add a slider in the UI, so you can scroll back in time, let you crop the data, etc. For now, I am developing features on-demand as I come up with new things to try. 

One thing I thought of was to allow you to annotate certain event with symbolic descriptions, such as "Starting compilation", "Parsing file blabla.java", "Emitting Code", etc. That would make scrolling through the timeline easier.

The last few days I spent at making it all a lot faster. Today I looked at supporting Python 2.7, because I want to explore some code that only runs on 2.7.

**Comment by laffra** [comment]
Before working too much in the Javascript, I think it makes sense to convert to TypeScript.

**Comment by pawamoy** [comment]
> annotate certain event

That is definitely a great idea!

I'm not at all fluent in Javascript nor TypeScript, but I can help on the Python side if you need any help, or on the data-format to record the calls maybe.

**Comment by laffra** [comment]
Check out the latest version. It has recording and playback support now. See the [README](https://github.com/laffra/pynsights) for description.

Here is a [recording](/pynsights_trace_main.html) I made today.

**Comment by laffra** [comment]
To help with stop/start of the recording, I added a timeline with annotations. This allows someone to observe what steps are taking when. See the [README](https://github.com/laffra/pynsights) for description. Interactive recording is [here](https://chrislaffra.com/pynsights_timeline.html). This completes this issue, I think.

**Comment by pawamoy** [comment]
Awesome! I'll try it out :slightly_smiling_face: Thanks!
